spring:
  application:
    name: energydata-api
  main:
    banner-mode: off

server:
  ssl:
    key-store: classpath:entsoe.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: entsoe
    key-password: password
  port: 443

entsoe:
  baseurl: "https://transparency.entsoe.eu/api"
